spring.application.name=hotel-management

# Database
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Security
jwt.secret-key=${JWT_SECRET}

# Frontend
frontend.url=${FRONTEND_URL}

# Payments
stripe.secret-key=${STRIPE_SECRET_KEY}
