spring.application.name=AirBnb


#DB
spring.datasource.url=jdbc:postgresql://localhost:9000/airBnb DB
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql = true
spring.datasource.password= root
spring.datasource.username=root

jwt.secreteKey = "user-secrete-Keyfjvbieubvorvjkbivbauiehfvajkfvbfv"

frontend_url = "http://localhost:8082"
#server.servlet.context-path=/api/v1

stripe.secrete.key = " "
